mutation createVehicle($photo: Upload, $data: CreateVehicleDTO!) {
  createVehicle(photo: $photo, data: $data) {
    id
    plate
    photo
    model
    modelYear
    color
    renavam
    chassisNumber
    fabricationYear
  }
}
