mutation createVehicle($photo: Upload, $data: CreateVehicleDTO!) {
  createVehicle(photo: $photo, data: $data) {
    ...VehicleFields
  }
}

mutation updateVehicle($id: Int!, $photo: Upload, $data: UpdateVehicleDTO!) {
  updateVehicle(photo: $photo, data: $data, id: $id) {
    ...VehicleFields
  }
}

mutation setVehicleTrackers($id: Int!, $trackerIds: [Int!]!) {
  setVehicleTrackers(id: $id, trackerIds: $trackerIds) {
    ...VehicleFields
    trackers {
      id
      identifier
      model
      simCards {
        id
        ssn
        apnUser
        apnAddress
        apnPassword
        phoneNumber
      }
    }
  }
}

mutation installNewTrackerOnVehicle($id: Int!, $tracker: CreateTrackerDTO!) {
  installNewTrackerOnVehicle(id: $id, tracker: $tracker) {
    ...VehicleFields
    trackers {
      id
      identifier
      model
    }
  }
}

mutation removeTrackerFromVehicle(
  $trackerId: Int!
  $removeSimsFromTracker: Boolean
) {
  removeTrackerFromVehicle(
    trackerId: $trackerId
    removeSimsFromTracker: $removeSimsFromTracker
  ) {
    id
    identifier
    model
    vehicle {
      id
    }
  }
}
