mutation createVehicle($photo: Upload, $data: CreateVehicleDTO!) {
  createVehicle(photo: $photo, data: $data) {
    ...VehicleFields
  }
}

mutation updateVehicle($id: Int!, $photo: Upload, $data: UpdateVehicleDTO!) {
  updateVehicle(photo: $photo, data: $data, id: $id) {
    ...VehicleFields
  }
}
