mutation loginMutation($credentials: LoginInput!) {
  login(credentials: $credentials) {
    token {
      value
      type
    }
    user {
      ... on UserModel {
        id
        email
        username
        emailVerified
        organization {
          id
          name
          billingEmail
          billingEmailVerified
        }
      }
    }
  }
}

mutation loginByTokenMutation($token: String!) {
  loginWithToken(token: $token) {
    token {
      value
      type
    }
    user {
      ... on UserModel {
        id
        email
        username
        emailVerified
      }
    }
  }
}
