mutation loginMutation($credentials: LoginInput!) {
  login(credentials: $credentials) {
    token {
      value
      type
    }
    user {
      id
      email
      username
      emailVerified
    }
  }
}

mutation loginByTokenMutation($token: String!) {
  loginWithToken(token: $token) {
    token {
      value
      type
    }
    user {
      id
      email
      username
      emailVerified
    }
  }
}
