query checkEmailInUse($email: String!) {
  isEmailInUse(email: $email)
}

query unregisteredUserByUuid($uuid: String!) {
  unregisteredUser(uuid: $uuid) {
    uuid
    email
    username
    emailVerified
  }
}
