query currentUserQuery {
  me {
    id
    email
    username
    emailVerified
  }
}

query isEmailInUseQuery($email: String!) {
  isEmailInUse(email: $email)
}

query unregisteredUserQuery($uuid: String!) {
  unregisteredUser(uuid: $uuid) {
    uuid
    email
    username
    emailVerified
  }
}
