version: '2.1'

orbs:
  node: circleci/node@5.0.0
  aws-s3: circleci/aws-s3@3.0
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build:
    executor:
      name: node/default
      tag: '14.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn global add @quasar/cli
          name: Install quasar cli
      - run:
          command: BUILD_FOR_HOMOLOG=true quasar build
          name: Build PWA
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --delete
          from: dist/homolog
          to: 's3://homolog.rastercar.com'
      - run:
          command: |
            aws cloudfront create-invalidation --distribution-id=E1REV6C7PKCAJZ --paths=/*
          name: Invalidate cloudfront distribution cache

workflows:
  main-workflow:
    jobs:
      - build:
        # Only bother deploying if were commiting to production (master) or homologation (homolog)
        filters:
          branches:
            only:
              - homolog
