export const vehicleColumns = [
  {
    name: 'plate',
    label: 'PLACA',
    field: 'plate',
    sortable: true,
    align: 'center' as const,
  },
  {
    name: 'model',
    label: 'Modelo',
    field: 'model',
    sortable: true,
    align: 'center' as const,
  },
  {
    name: 'modelYear',
    label: 'Ano Modelo',
    field: 'modelYear',
    sortable: true,
    align: 'center' as const,
  },
  {
    name: 'color',
    label: 'Cor',
    field: 'color',
    sortable: true,
    align: 'center' as const,
  },
  {
    name: 'renavam',
    label: 'Renavam',
    field: 'renavam',
    sortable: true,
    align: 'center' as const,
  },
  {
    name: 'chassisNumber',
    label: 'Chassi',
    field: 'chassisNumber',
    sortable: true,
    align: 'center' as const,
  },
  {
    name: 'fabricationYear',
    label: 'Ano Fabricação',
    field: 'fabricationYear',
    sortable: true,
    align: 'center' as const,
  },
]
