query listOrganizations {
  organizations {
    id
    name
    billingEmail
    billingEmailVerified
  }
}

query organizationById($id: Int!) {
  organization(id: $id) {
    id
    name
    billingEmail
    billingEmailVerified
  }
}
