mutation setTrackerSimCards($id: Int!, $simCardIds: [Int!]!) {
  setTrackerSimCards(id: $id, simCardIds: $simCardIds) {
    id
    simCards {
      id
      ssn
      apnUser
      apnAddress
      apnPassword
    }
  }
}

mutation installNewSimCardOnTracker(
  $trackerId: Int!
  $simCard: CreateSimCardDTO!
) {
  installNewSimCardOnTracker(id: $trackerId, simCard: $simCard) {
    id
    model
    identifier
    simCards {
      id
      ssn
      phoneNumber
      apnUser
      apnAddress
      apnPassword
    }
  }
}
