mutation setTrackerSimCards($id: Int!, $simCardIds: [Int!]!) {
  setTrackerSimCards(id: $id, simCardIds: $simCardIds) {
    ...TrackerScalarFields
    simCards {
      ...SimCardScalarFields
    }
  }
}

mutation installNewSimCardOnTracker(
  $trackerId: Int!
  $simCard: CreateSimCardDTO!
) {
  installNewSimCardOnTracker(id: $trackerId, simCard: $simCard) {
    ...TrackerScalarFields
    simCards {
      ...SimCardScalarFields
    }
  }
}

mutation removeTrackerFromVehicle(
  $trackerId: Int!
  $removeSimsFromTracker: Boolean
) {
  removeTrackerFromVehicle(
    trackerId: $trackerId
    removeSimsFromTracker: $removeSimsFromTracker
  ) {
    ...TrackerScalarFields
  }
}
