query listActiveTrackers {
  activeTrackers {
    id
    identifier
    model
    lastPosition {
      lat
      lng
    }
    vehicle {
      id
      plate
      model
      brand
    }
  }
}

query listTrackers(
  $offset: Int
  $limit: Int
  $orderBy: String
  $descending: Boolean
  $search: String
  $installedOnVehicle: Boolean
) {
  trackers(
    offset: $offset
    limit: $limit
    orderBy: $orderBy
    descending: $descending
    search: $search
    installedOnVehicle: $installedOnVehicle
  ) {
    nodes {
      ...TrackerScalarFields
    }
    pageInfo {
      total
      hasMore
      hasPrevious
    }
  }
}
