mutation removeSimCardFromTracker($simCardId: Int!) {
  removeSimCardFromTracker(id: $simCardId) {
    id
    ssn
    phoneNumber
    apnUser
    apnAddress
    apnPassword
    tracker {
      id
    }
  }
}
