mutation registerUser($user: RegisterUserDTO!) {
  register(user: $user) {
    token {
      value
      type
    }
    user {
      ... on UserModel {
        ...FullUser
      }
      ... on MasterUserModel {
        ...FullMasterUser
      }
    }
  }
}

mutation updateMyProfile($profileData: UpdateUserDTO!) {
  updateMyProfile(profileData: $profileData) {
    ...UserSimpleFields
  }
}
