query currentUserQuery {
  me {
    ... on UserModel {
      ...FullUser
    }
    ... on MasterUserModel {
      ...FullMasterUser
    }
  }
}

query userByIdQuery($id: Int!) {
  user(id: $id) {
    ...FullUser
  }
}
