mutation registerUserMutation($user: RegisterUserDTO!) {
  register(user: $user) {
    token {
      value
      type
    }
    user {
      ... on UserModel {
        id
        email
        username
        emailVerified
        organization {
          id
          name
          billingEmail
          billingEmailVerified
        }
      }
    }
  }
}
