query currentUser {
  me {
    ... on UserModel {
      ...FullUser
    }
    ... on MasterUserModel {
      ...FullMasterUser
    }
  }
}

query currentUserSimple {
  me {
    ... on UserModel {
      ...UserSimpleFields
    }
    ... on MasterUserModel {
      ...MasterUserSimpleFields
    }
  }
}

query userById($id: Int!) {
  user(id: $id) {
    ...FullUser
  }
}
