fragment UserScalarFields on UserModel {
  email
  emailVerified
  googleProfileId
  id
  username
}

fragment FullUser on UserModel {
  ...UserScalarFields
  organization {
    id
    name
    blocked
    billingEmail
    billingEmailVerified
  }
  accessLevel {
    id
    name
    permissions
  }
}

fragment MasterUserScalarFields on MasterUserModel {
  id
  email
  username
  emailVerified
}

fragment FullMasterUser on MasterUserModel {
  ...MasterUserScalarFields
  accessLevel {
    id
    name
    permissions
  }
  masterAccessLevel {
    id
    name
    permissions
  }
}
