fragment FullUser on UserModel {
  id
  email
  username
  emailVerified
  googleProfileId
  organization {
    id
    name
    billingEmail
    billingEmailVerified
  }
  accessLevel {
    id
    name
    permissions
  }
}

fragment UserSimpleFields on UserModel {
  id
  email
  username
  emailVerified
  googleProfileId
}

fragment MasterUserSimpleFields on MasterUserModel {
  id
  email
  username
  emailVerified
}

fragment FullMasterUser on MasterUserModel {
  id
  email
  username
  emailVerified
  accessLevel {
    id
    name
    permissions
  }
  masterAccessLevel {
    id
    name
    permissions
  }
}
